"""empty message

Revision ID: 21b392a27255
Revises: 4589f78ec2ed
Create Date: 2016-05-01 12:13:01.236458

"""

# revision identifiers, used by Alembic.
revision = '21b392a27255'
down_revision = '4589f78ec2ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
