"""empty message

Revision ID: 2c7877e73705
Revises: None
Create Date: 2016-04-26 22:09:27.603115

"""

# revision identifiers, used by Alembic.
revision = '2c7877e73705'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
