"""empty message

Revision ID: 309990f409a8
Revises: 380957534a49
Create Date: 2016-05-11 15:20:51.417875

"""

# revision identifiers, used by Alembic.
revision = '309990f409a8'
down_revision = '380957534a49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
