"""empty message

Revision ID: 35557b5e3ad7
Revises: 21b392a27255
Create Date: 2016-05-03 18:09:45.381004

"""

# revision identifiers, used by Alembic.
revision = '35557b5e3ad7'
down_revision = '21b392a27255'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
