"""empty message

Revision ID: 4589f78ec2ed
Revises: 2c7877e73705
Create Date: 2016-04-27 01:01:41.249798

"""

# revision identifiers, used by Alembic.
revision = '4589f78ec2ed'
down_revision = '2c7877e73705'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
