"""empty message

Revision ID: 49376ba7f3f6
Revises: 2c92d7aa0352
Create Date: 2016-05-07 20:32:56.107673

"""

# revision identifiers, used by Alembic.
revision = '49376ba7f3f6'
down_revision = '2c92d7aa0352'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
