"""empty message

Revision ID: 4cb16bda99d8
Revises: 35557b5e3ad7
Create Date: 2016-05-03 19:03:03.490990

"""

# revision identifiers, used by Alembic.
revision = '4cb16bda99d8'
down_revision = '35557b5e3ad7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
