"""empty message

Revision ID: 56db22167f6
Revises: 39b7a9380933
Create Date: 2016-05-31 13:54:03.601425

"""

# revision identifiers, used by Alembic.
revision = '56db22167f6'
down_revision = '39b7a9380933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
