"""empty message

Revision ID: 7ea52a35b18
Revises: 56db22167f6
Create Date: 2016-05-31 13:54:10.826008

"""

# revision identifiers, used by Alembic.
revision = '7ea52a35b18'
down_revision = '56db22167f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
